ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "fastai"
  site-url: "https://docs.fast.ai/"
  description: "fastai simplifies training fast and accurate neural nets using modern best practices"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: "https://github.com/fastai/fastai"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/fastai/fastai"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
